#-------------------------------
# Site Settings
title: Enhancing Audio Description
logo: # /images/EAD-old-logo.png
description: Project website for Enhancing Audio Description
baseurl: # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site, e.g. http://example.com
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Author Settings
author:
  author__name: EAD
  author__bio: We are a team of ...
  author__avatar: '/images/EAD-old-logo.png'

social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
# - {icon: "ion-logo-instagram", link: "https://instagram.com"}
# - {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-youtube", link: "https://youtube.com"}

# Example of adding a new link to the footer - {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Hero Settings
hero:
  hero__title: Hello!
  hero__description: ‘Enhancing Audio Description’ or ‘Enhancing AD’ is a project that seeks to explore how sound design techniques can be used to rethink accessibility to film and television for visually impaired audiences. Research will include the application of surround sound rendering, interactive media systems and first person narration. EAD is funded by the Arts and Humanities Research Council AH/N003713/1.
  hero__image: '/images/2017-04-13-binaural-listening-test-for-accessibility.jpg'


#-------------------------------
# Newsletter
mailchimp: enable # To enable the mailchimp form, use the value 'enable'. To disable the form, leave the field blank.
mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
mailchimp__input__text: Your email address
mailchimp__button__text: Subscribe to our mailinglist


#-------------------------------
# Gallery Footer Section
gallery:
  gallery__title: Gallery
  gallery__columns: 3
  gallery__images:
    - alt: 'Focus group in Cambridge with Mariana'
      url: '/images/2016-08-25-survey-and-focus-groups.jpg'
    - alt: 'Krisztian playing audio games'
      url: '/images/2016-10-14-more-on-audio-games.jpg'
    - alt: 'Binaural listening test room'
      url: '/images/2017-04-13-binaural-listening-test-for-accessibility.jpg'
    - alt: 'Screenshot from the Pearl short film'
      url: '/images/2016-08-25-survey-and-focus-groups-pearl-screenshot.jpg'
    - alt: 'Conference hallway with people'
      url: '/images/2017-11-14-conference-on-accessibility-in-film-television-and-interactive-media-selected-photos-09-narrow.jpg'
    - alt: 'Conference poster presentations'
      url: '/images/2017-11-14-conference-on-accessibility-in-film-television-and-interactive-media-selected-photos-gallery-narrow-1.jpg'
    - alt: 'Conference activity'
      url: '/images/2017-11-14-conference-on-accessibility-in-film-television-and-interactive-media-selected-photos-gallery-narrow-2.jpg'
    - alt: 'Mariana talking to an audience'
      url: '/images/2017-11-16-review-on-our-conference.jpg'
    - alt: 'Screenshot from the Shelf Life short film'
      url: '/images/2018-03-29-shelf-life.jpg'


#-------------------------------
# Contact Settings
contact:
  email: krisztian.hofstadter@york.ac.uk # Add your email for contant form
  description: Thanks for your interest in our EAD project. Please get in touch if you have any questions about our work or have feedback on our website’s accessibility. # Add a description of your form

# NOTE
# Menso theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example demo-menca


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id


#-------------------------------
# Build Settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext


include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed